### ISSUE TITLE
A display issue with localization

### ISSUE THREAD

**Issue by EVINK** [dbrekalo/vue-date-pick#45]
Very wonderful vue component, but there is a issue while using it with localization.

↓↓↓
![屏幕快照 2020-03-28 下午1 42 25](https://user-images.githubusercontent.com/14816851/77815989-2dc15000-70fa-11ea-9620-073f5f108211.png)

Weeks here should be arranged horizontally, but it is goes vertically. It is not a very big problem, just a little different weird from the custom.

**Comment by EVINK** [comment]
Use css property white-space
```css
    /deep/ .vdpHeadCellContent {
        white-space: nowrap;
    }
```
Problem solved!
