### ISSUE TITLE
Safari: Clicks on a month or year don't bring up drop-downs unless you position cursor up

### ISSUE THREAD

**Issue by DKroot** [dbrekalo/vue-date-pick#77]
I'm running into a usability issue in Safari. Clicks on a month or year don't bring up drop-downs unless you position cursor up: 5-10 px or so. Chrome doesn't exhibit this issue. I'm testing on macOS Catalina, Safari v14.0.3.

BTW, the following CSS snippet, courtesy of @tcuongtran resolves the issue:
```CSS
    .vdpPeriodControl > select {
      /* Fix for a problem with month and year cursor positioning in Safari */
      -webkit-appearance: menulist-button;
    }
```
